# -*- coding: utf-8 -*-
"""BAYESIAN NETWORK7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10Y-K9kORkk55PB_pfMXwZnJOmeQzwMHg
"""

import numpy as np
from urllib.request import urlopen
import urllib

!pip install pgmpy

import pandas as pd

from pgmpy.inference import VariableElimination
from pgmpy.models import BayesianNetwork
from pgmpy.estimators import MaximumLikelihoodEstimator, BayesianEstimator



heartDisease.describe()

print(heartDisease.columns)

print(heartDisease.isnull().sum())

names = ['age','sex','cp','trestbps','chol','fbs','restecg','thalach','exang','oldpeak','slope','ca','thal','target']
heartDisease = pd.read_csv("/content/healthcare  dataset - healthcare  dataset.csv")
heartDisease = heartDisease.replace('?',np.nan)

model = BayesianNetwork([('age','trestbps'), ('age','fbs'), ('sex','trestbps'), ('exang','trestbps'),('trestbps','target'),('fbs','target'),('target','restecg'),
('target','thalach'), ('target','chol')])

model.fit(heartDisease, estimator=MaximumLikelihoodEstimator)

from pgmpy.inference import VariableElimination
HeartDisease_infer = VariableElimination(model)

q = HeartDisease_infer.query(variables=['target'], evidence={'age':37,'sex':0})

print(q)